api:
  pokemon:
    url: https://pokeapi.co/api/v2/
  jsonplaceholder:
    url: https://jsonplaceholder.typicode.com/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# Common
spring:
  application.name: demo
  profiles:
    active:
      - local-dev
  jmx.enabled: false
  application.admin.enabled: false
  jackson:
    default-property-inclusion: non-null

server:
    port: 8080
    error:
      include-stacktrace: always
      whitelabel.enabled: false
